require 'App.Modulus.UI.UIMgr.UIMgr'
require 'App.Modulus.UI.UIMgr.TipsMgr'
require 'App.Modulus.UI.UIMgr.PromptMgr'
require 'App.Modulus.UI.UIMgr.UIFloatMgr'
require 'App.Modulus.UI.UIMgr.UIBubbleMgr'