using System;
using System.Collections.Generic;
namespace SLua {
	[LuaBinder(1)]
	public class BindUnityUI {
		public static Action<IntPtr>[] GetBindList() {
			Action<IntPtr>[] list= {
				Lua_UnityEngine_UI_Button.reg,
				Lua_UnityEngine_UI_Graphic.reg,
				Lua_UnityEngine_EventSystems_BaseRaycaster.reg,
				Lua_UnityEngine_UI_GraphicRaycaster.reg,
				Lua_UnityEngine_UI_GraphicRegistry.reg,
				Lua_UnityEngine_UI_IMaskable.reg,
				Lua_UnityEngine_UI_MaskableGraphic.reg,
				Lua_UnityEngine_UI_Image.reg,
				Lua_UnityEngine_UI_Mask.reg,
				Lua_UnityEngine_UI_MaskUtilities.reg,
				Lua_UnityEngine_UI_RectMask2D.reg,
				Lua_UnityEngine_UI_Slider.reg,
				Lua_UnityEngine_UI_Text.reg,
				Lua_UnityEngine_UI_Toggle.reg,
				Lua_UnityEngine_UI_ToggleGroup.reg,
				Lua_UnityEngine_UI_Outline.reg,
				Lua_UnityEngine_EventSystems_AbstractEventData.reg,
				Lua_UnityEngine_EventSystems_BaseEventData.reg,
				Lua_UnityEngine_EventSystems_PointerEventData.reg,
				Lua_UnityEngine_EventSystems_EventHandle.reg,
				Lua_UnityEngine_EventSystems_IEventSystemHandler.reg,
				Lua_UnityEngine_EventSystems_IPointerEnterHandler.reg,
				Lua_UnityEngine_EventSystems_IPointerExitHandler.reg,
				Lua_UnityEngine_EventSystems_IPointerDownHandler.reg,
				Lua_UnityEngine_EventSystems_IPointerUpHandler.reg,
				Lua_UnityEngine_EventSystems_IPointerClickHandler.reg,
				Lua_UnityEngine_EventSystems_IBeginDragHandler.reg,
				Lua_UnityEngine_EventSystems_IInitializePotentialDragHandler.reg,
				Lua_UnityEngine_EventSystems_IDragHandler.reg,
				Lua_UnityEngine_EventSystems_IEndDragHandler.reg,
				Lua_UnityEngine_EventSystems_IDropHandler.reg,
				Lua_UnityEngine_EventSystems_IScrollHandler.reg,
				Lua_UnityEngine_EventSystems_IUpdateSelectedHandler.reg,
				Lua_UnityEngine_EventSystems_ISelectHandler.reg,
				Lua_UnityEngine_EventSystems_IDeselectHandler.reg,
				Lua_UnityEngine_EventSystems_IMoveHandler.reg,
				Lua_UnityEngine_EventSystems_ISubmitHandler.reg,
				Lua_UnityEngine_EventSystems_ICancelHandler.reg,
				Lua_UnityEngine_EventSystems_EventSystem.reg,
				Lua_UnityEngine_EventSystems_EventTrigger.reg,
				Lua_UnityEngine_EventSystems_EventTriggerType.reg,
				Lua_UnityEngine_EventSystems_ExecuteEvents.reg,
				Lua_UnityEngine_EventSystems_MoveDirection.reg,
				Lua_UnityEngine_EventSystems_RaycastResult.reg,
				Lua_UnityEngine_EventSystems_RaycasterManager.reg,
				Lua_UnityEngine_UI_Button_ButtonClickedEvent.reg,
				Lua_UnityEngine_UI_GraphicRaycaster_BlockingObjects.reg,
				Lua_UnityEngine_UI_Image_Type.reg,
				Lua_UnityEngine_UI_Image_FillMethod.reg,
				Lua_UnityEngine_UI_Image_OriginHorizontal.reg,
				Lua_UnityEngine_UI_Image_OriginVertical.reg,
				Lua_UnityEngine_UI_Image_Origin90.reg,
				Lua_UnityEngine_UI_Image_Origin180.reg,
				Lua_UnityEngine_UI_Image_Origin360.reg,
				Lua_UnityEngine_UI_MaskableGraphic_CullStateChangedEvent.reg,
				Lua_UnityEngine_UI_Slider_Direction.reg,
				Lua_UnityEngine_UI_Slider_SliderEvent.reg,
				Lua_UnityEngine_UI_Toggle_ToggleTransition.reg,
				Lua_UnityEngine_UI_Toggle_ToggleEvent.reg,
				Lua_UnityEngine_EventSystems_PointerEventData_FramePressState.reg,
				Lua_UnityEngine_EventSystems_EventTrigger_TriggerEvent.reg,
				Lua_UnityEngine_EventSystems_EventTrigger_Entry.reg,
			};
			return list;
		}
	}
}
