require 'App.Modulus.UI.UIConf.__init'
require 'App.Modulus.UI.UIData.__init'
require 'App.Modulus.UI.UIWidget.__init'
require 'App.Modulus.UI.UIBase.__init'
require 'App.Modulus.UI.UIStencil.__init'
require 'App.Modulus.UI.UIMonitor.__init'
require 'App.Modulus.UI.UIMgr.__init'
require 'App.Modulus.UI.UIUtils.__init'