TestPrefabCmd={}

TestPrefabCmd.Open_TestPrefab_UI="Open_TestPrefab_UI"
TestPrefabCmd.Close_TestPrefab_UI="Close_TestPrefab_UI"
TestPrefabCmd.OnOpen_TestPrefab_UI="OnOpen_TestPrefab_UI"
TestPrefabCmd.OnClose_TestPrefab_UI="OnClose_TestPrefab_UI"